global:
    settings:
        dinkly_version: "3.06"
        time_format: h:i a
        languages:
            english:
                - en
                - en_US
            french: 
                - fr
                - fr_FR

    apps:
        demo:
            base_href: /
            default_app: true
            default_module: landing
            enabled: true
            app_name: Dinkly Demo
            app_description: The biggest little MVC Framework

    plugins:

    databases: #First entry will be default
        demo:
            host: localhost
            user: root
            pass: root
            name: dinkly_app

dev:
    #Put dev environment overrides here
    settings:

    apps:
        
    plugins:

    databases:
